# Generated by Django 4.1.3 on 2022-12-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mavuno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(db_index=True, default='Nairobi', max_length=200),
            preserve_default=False,
        ),
    ]
